_homepage:
    pattern: /
    defaults: { _controller: MyValleyBundle:Default:index }

my_valley:
    resource: "@MyValleyBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults: { _controller: MyValleyBundle:Default:index }

my_helloworld:
    resource: "@MyHelloworldBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

