_homepage:
    pattern: /
    defaults: { _controller: MyLakeBundle:Default:index }

my_lakee:
    resource: "@MyLakeeBundle/Resources/config/routing.xml"
    prefix:   /

my_lake:
    resource: "@MyLakeBundle/Controller/"
    type:     annotation
    prefix:   /



my_valley:
    resource: "@MyValleyBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults: { _controller: MyValleyBundle:Default:index }

my_helloworld:
    resource: "@MyHelloworldBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

